shfmt

diff --git a/bin/merge-main-branch b/bin/merge-main-branch
--- a/bin/merge-main-branch
+++ b/bin/merge-main-branch
@@ -4,7 +4,7 @@
 
 set -eu -o pipefail
 
-error () {
+error() {
     echo "error: ${*}" >&2
     exit 1
 }
@@ -18,17 +18,17 @@ DST="$2"
 WORKDIR=$(mktemp -d)
 
 packages_in_suite() {
-   local suite="$1"
-   [ -n "$suite" ] || return 1
-   ssh reprepro@incoming.deb.tails.boum.org reprepro list "$suite" \
-       | sed -r 's,^([^|]+\|){2},,' \
-       | sort --stable --key=1,1 --key=2,2
+    local suite="$1"
+    [ -n "$suite" ] || return 1
+    ssh reprepro@incoming.deb.tails.boum.org reprepro list "$suite" |
+        sed -r 's,^([^|]+\|){2},,' |
+        sort --stable --key=1,1 --key=2,2
 }
 
 ### Save the list of packages currently present in the APT suite we
 ### want to merge into
 
-packages_in_suite "$DST" > "$WORKDIR/$DST.orig.list"
+packages_in_suite "$DST" >"$WORKDIR/$DST.orig.list"
 
 ### Make sure we are not going to overwrite newer packages with older
 ### ones
@@ -61,13 +61,13 @@ ssh reprepro@incoming.deb.tails.boum.org \
     tails-merge-suite "$SRC" "$DST"
 
 echo "I: Restoring config/base_branch on $DST if needed"
-echo "${DST}" > config/base_branch
+echo "${DST}" >config/base_branch
 git commit config/base_branch -m "Restore ${DST}'s base branch." || :
 
 echo "I: Pushing the $DST Git branch"
 git push origin "${DST}:${DST}"
 
-packages_in_suite "$DST" > "$WORKDIR/$DST.new.list"
+packages_in_suite "$DST" >"$WORKDIR/$DST.new.list"
 
 echo "I: Diff between the $DST APT suite before and after merging:"
 set +e
@@ -75,18 +75,18 @@ diff -Naur "$WORKDIR/$DST.orig.list" "$WORKDIR/$DST.new.list"
 RET=$?
 set -e
 case "$RET" in
-   0|1)
-      # diff did its job just fine
-      :
-      ;;
-   2)
-      # diff had trouble
-      error "diff(1) failed."
-      ;;
-   *)
-      # undocumented diff exit code
-      error "diff(1) returned $? -- I don't know what it means."
-      ;;
+0 | 1)
+    # diff did its job just fine
+    :
+    ;;
+2)
+    # diff had trouble
+    error "diff(1) failed."
+    ;;
+*)
+    # undocumented diff exit code
+    error "diff(1) returned $? -- I don't know what it means."
+    ;;
 esac
 echo "Verify that the merge did not re-add to $DST any package that was"
 echo "removed from it on purpose earlier."
