Ensure Tor Browser is only started inside a flatpak

diff --git a/config/chroot_local-includes/usr/bin/tor-browser b/config/chroot_local-includes/usr/bin/tor-browser
--- a/config/chroot_local-includes/usr/bin/tor-browser
+++ b/config/chroot_local-includes/usr/bin/tor-browser
@@ -82,6 +82,11 @@ start_browser() {
         "${@}"
 }
 
+if ! [ -f /.flatpak-info ]; then
+    echo >&2 "Error: Must be run in flatpak"
+    exit 1
+fi
+
 if tor_has_bootstrapped || ask_for_confirmation; then
     # Torbutton 1.5.1+ uses those environment variables
     export TOR_SOCKS_HOST='127.0.0.1'
