determine directory name automatically
that's similar to /usr/share/go-*, but it doesn't fail when there is
more than one result

diff --git a/config/chroot_local-includes/usr/local/lib/build-https-accept-expired b/config/chroot_local-includes/usr/local/lib/build-https-accept-expired
--- a/config/chroot_local-includes/usr/local/lib/build-https-accept-expired
+++ b/config/chroot_local-includes/usr/local/lib/build-https-accept-expired
@@ -19,7 +19,12 @@ else
     DST="https-get-expired"
 fi
 
-cp /usr/share/go-1.26/src/crypto/tls/cache.go "$SRCDIR"
+goDir=$(find /usr/share/ -maxdepth 1 -name 'go-*' -type d | head -n1)
+if [ -z "$goDir" ]; then
+    echo "Could not find a go installation, aborting" >&2
+    exit 1
+fi
+cp "${goDir}/src/crypto/tls/cache.go" "$SRCDIR"
 sed -i -e '0,/^package tls/s//package main/' "$SRCDIR/cache.go"
 go build -v -ldflags=-buildid= -trimpath -o "$DST" "$SRC" "$SRCDIR/cache.go"
 strip --strip-all "$DST"
