shfmt

diff --git a/config/chroot_local-includes/usr/local/lib/tails-run-tor-browser-in-flatpak b/config/chroot_local-includes/usr/local/lib/tails-run-tor-browser-in-flatpak
--- a/config/chroot_local-includes/usr/local/lib/tails-run-tor-browser-in-flatpak
+++ b/config/chroot_local-includes/usr/local/lib/tails-run-tor-browser-in-flatpak
@@ -5,12 +5,12 @@ set -eu
 # Check that no argument begins with a '-', so that URIs can be passed
 # but options cannot. See #19595.
 for arg in "$@"; do
-  case "$arg" in
-  -*)
-    echo "Error: option '$arg' not supported" >&2
-    exit 1
-    ;;
-  esac
+    case "$arg" in
+    -*)
+        echo "Error: option '$arg' not supported" >&2
+        exit 1
+        ;;
+    esac
 done
 
 # Avoid that Flatpak prints a warning about its exports directories not
@@ -24,10 +24,10 @@ export FLATPAK_FANCY_OUTPUT=0
 # Before doing so, save the environment in a file, so that we can pass
 # it to the Tor Browser process later.
 if [ "$(id -u)" = 1000 ]; then
-  ENVFILE=$(mktemp --suffix -env)
-  export ENVFILE
-  env --null >"${ENVFILE}"
-  exec sudo "$0" "$@"
+    ENVFILE=$(mktemp --suffix -env)
+    export ENVFILE
+    env --null >"${ENVFILE}"
+    exec sudo "$0" "$@"
 fi
 
 # Explanation of the following command:
@@ -50,7 +50,7 @@ fi
 #    the actual Tor Browser process in a Flatpak sandbox.
 
 exec \
-  /bin/ip netns exec tbb \
-  sudo -u amnesia -- \
-  /usr/local/lib/run-with-env --env-file="${ENVFILE}" --delete -- \
-  flatpak run --command=tor-browser org.boum.tails.TorBrowser "$@"
+    /bin/ip netns exec tbb \
+    sudo -u amnesia -- \
+    /usr/local/lib/run-with-env --env-file="${ENVFILE}" --delete -- \
+    flatpak run --command=tor-browser org.boum.tails.TorBrowser "$@"
