also report locales
yes, this block will include what's reported by the previous block, so
it's redundant and could be removed.
But having the list of apps easily accessible is very practical for us,
so let's waste those bytes.

diff --git a/config/chroot_local-includes/usr/local/lib/tails-flatpak-info b/config/chroot_local-includes/usr/local/lib/tails-flatpak-info
--- a/config/chroot_local-includes/usr/local/lib/tails-flatpak-info
+++ b/config/chroot_local-includes/usr/local/lib/tails-flatpak-info
@@ -16,17 +16,24 @@ run_flatpak() {
     "${flatpakCmd[@]}" "--${scope}" list --show-details "--${selection}" 2>&1
 }
 
+report() {
+    scope="$1"
+    selection="$2"
+    name="$3"
+    echo "## ${name} installed ${scope}-level:"
+    set +e
+    run_flatpak "${scope}" "${selection}"
+    ret=$?
+    set -e
+    if [ $ret -ne 0 ]; then
+        echo "ERROR $ret"
+    fi
+}
+
 for scope in user system; do
-    for selection in runtime app; do
-        echo "## ${selection}s installed ${scope}-level:"
-        set +e
-        run_flatpak "${scope}" "${selection}"
-        ret=$?
-        set -e
-        if [ $ret -ne 0 ]; then
-            echo "ERROR $ret"
-        fi
-    done
+    report "$scope" runtime runtimes
+    report "$scope" app apps
+    report "$scope" all everything
 done
 
 exit 0
