build-tails: add a 2 minute timeout for NTP synchronization
Otherwise NTP issues can lead to and endless loop so the build must be
aborted manually (refs: tails#21355).

diff --git a/vagrant/provision/assets/build-tails b/vagrant/provision/assets/build-tails
--- a/vagrant/provision/assets/build-tails
+++ b/vagrant/provision/assets/build-tails
@@ -174,8 +174,14 @@ fi
 if [ "${TAILS_OFFLINE_MODE}" != 1 ]; then
     as_root_do timedatectl set-ntp true
     set +x
+    ELAPSED=0
     echo -n "Waiting for the time to be synchronized..."
     while ! ntp_synchronized; do
+        if [ "${ELAPSED}" -ge 120 ]; then
+            echo "NTP synchronization didn't succeed within 2 minutes, aborting..." >&2
+            exit 1
+        fi
+        ELAPSED=$((ELAPSED + 1))
         sleep 1
         echo -n "."
     done
